In [1]:
#Import Libraries

import warnings

warnings.filterwarnings("ignore")

# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd
import xlwings as xw

In [2]:
# Import the os module
import os

# Get the current working directory
cwd = os.getcwd()

# Print the current working directory
print("Current working directory: {0}".format(cwd))

# Print the type of the returned object
print("os.getcwd() returns an object of type: {0}".format(type(cwd)))

Current working directory: C:\Users\abasalay\Downloads
os.getcwd() returns an object of type: <class 'str'>

In [3]:
#Go to Z: drive
os.startfile("Z:Scheduling_Engineering_Production//Production Log Schedule")

In [4]:
Productionlog = "Cozzini Production Log.xlsx" #this is the destination file for the tracker
Shipmentsheet= "C://Users//abasalay//OneDrive - Middleby//TestSheet.xlsx" #this is the file I want to read the Active sheet from

In [5]:

PATH = 'Z:Scheduling_Engineering_Production/Production Log Schedule/Cozzini Order Production Log.xlsm'
wb = xw.Book(PATH)
sheet = wb.sheets['ACTIVE']

df = sheet['A1:AN500'].options(pd.DataFrame, index=False, header=False).value
df

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,PO,TYPE,None,Mfg Loc,None,None,None,None,Proj,Elec,...,None,None,None,Quoted,Revised,Rev,Rev,Inter-Comp,Final,ONSITE
2,None,None,Proj #,Job #,QTY,Customer,Part #,Description,MGR,Eng,...,M,B,O,Ship Date,Ship Date,Ship Date2,Ship Date3,Ship Date,Ship Date,AT CUSTOMER
3,2022-04-12 00:00:00,None,P21396,91259.0,1.0,"BAR-S ALTUS, OK",None,VS922 VACUUM EMULSION SYSTEM,DM,MB,...,None,None,None,2022-09-23 00:00:00,2022-10-17 00:00:00,2022-10-31 00:00:00,2023-01-31 00:00:00,None,2023-01-31 00:00:00,None
4,2022-12-21 00:00:00,None,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",None,GUARDING PACKAGE FOR P21182,DM,N/A,...,None,None,None,2023-01-31 00:00:00,None,None,None,None,2023-01-31 00:00:00,want to ship w/ diverter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
496,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
497,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
498,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
499,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [6]:
df.columns.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int64)

In [7]:
#drop first three rows
df.drop(index=df.index[0:3], axis=0, inplace=True)
df

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
3,2022-04-12 00:00:00,None,P21396,91259.0,1.0,"BAR-S ALTUS, OK",None,VS922 VACUUM EMULSION SYSTEM,DM,MB,...,None,None,None,2022-09-23 00:00:00,2022-10-17 00:00:00,2022-10-31 00:00:00,2023-01-31 00:00:00,None,2023-01-31 00:00:00,None
4,2022-12-21 00:00:00,None,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",None,GUARDING PACKAGE FOR P21182,DM,N/A,...,None,None,None,2023-01-31 00:00:00,None,None,None,None,2023-01-31 00:00:00,want to ship w/ diverter
5,2022-02-28 00:00:00,None,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,"CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,Steve Ward to visit
6,2022-02-28 00:00:00,None,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,"CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,None
7,2022-02-28 00:00:00,None,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
496,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
497,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
498,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
499,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [8]:
# create a dictionary
# key = old name
# value = new name
dict = {0:'PO Date', 1:'Type',2:'Project Number', 3:'Shop Order', 4: 'Qty', 5:'Customer', 6:'PN', 7: 'Line_Item',
       8: 'PE', 9:'EE',10:'DES?',11:'Design Chicago',12: 'Design Iowa', 13: 'Design Mexico', 14:'Design B',15: 'MFG O', 16:'DE1',
       17:'DE', 18:'Design Due', 19:'Mfg Dwg start', 20:'Mfg Dwg rec', 21:'Mfg Comp date', 23: 'MFG Chicago',
        24:'MFG Iowa', 25: 'MFG Mexico', 26: 'MFG B', 27: 'MFG O.1', 28: 'Ship from Chicago', 29:'Ship from Iowa', 30:'Ship from Mexico',
        31:'Ship from B', 32:'Ship from O', 33:'Quoted Ship', 34: 'Revised Ship', 35:'R2 Ship', 36:'R3 Ship', 37:'Inter-Comp Ship', 38:'Final Ship', 39:'Notes'
       }
 
# call rename () method
df.rename(columns=dict,
          inplace=True)
 
# print Data frame after rename columns
display(df)

#Rename rest of columns after test proves it works

,PO Date,Type,Project Number,Shop Order,Qty,Customer,PN,Line_Item,PE,EE,...,Ship from Mexico,Ship from B,Ship from O,Quoted Ship,Revised Ship,R2 Ship,R3 Ship,Inter-Comp Ship,Final Ship,Notes
3,2022-04-12 00:00:00,None,P21396,91259.0,1.0,"BAR-S ALTUS, OK",None,VS922 VACUUM EMULSION SYSTEM,DM,MB,...,None,None,None,2022-09-23 00:00:00,2022-10-17 00:00:00,2022-10-31 00:00:00,2023-01-31 00:00:00,None,2023-01-31 00:00:00,None
4,2022-12-21 00:00:00,None,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",None,GUARDING PACKAGE FOR P21182,DM,N/A,...,None,None,None,2023-01-31 00:00:00,None,None,None,None,2023-01-31 00:00:00,want to ship w/ diverter
5,2022-02-28 00:00:00,None,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,"CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,Steve Ward to visit
6,2022-02-28 00:00:00,None,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,"CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,None
7,2022-02-28 00:00:00,None,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",None,EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,...,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,None,2023-02-01 00:00:00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
496,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
497,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
498,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
499,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [9]:
# Drop all columns that don't contain any data

df=df.drop(['Type', 'PN', 'DES?', 'Design Chicago', 'Design Iowa', 'Design B', 'Design Mexico', 'MFG O', 'DE1', 'Design Due', 'Mfg Dwg start', 'Ship from Chicago', 'Ship from Iowa', 'Ship from B', 'Ship from O','Ship from Mexico', 'Inter-Comp Ship'], axis=1)
df

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,MFG Iowa,MFG Mexico,MFG B,MFG O.1,Quoted Ship,Revised Ship,R2 Ship,R3 Ship,Final Ship,Notes
3,2022-04-12 00:00:00,P21396,91259.0,1.0,"BAR-S ALTUS, OK",VS922 VACUUM EMULSION SYSTEM,DM,MB,FW,None,...,None,None,None,None,2022-09-23 00:00:00,2022-10-17 00:00:00,2022-10-31 00:00:00,2023-01-31 00:00:00,2023-01-31 00:00:00,None
4,2022-12-21 00:00:00,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",GUARDING PACKAGE FOR P21182,DM,N/A,FW,None,...,None,None,None,None,2023-01-31 00:00:00,None,None,None,2023-01-31 00:00:00,want to ship w/ diverter
5,2022-02-28 00:00:00,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,Steve Ward to visit
6,2022-02-28 00:00:00,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,None
7,2022-02-28 00:00:00,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,NA,None,...,None,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
496,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
497,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
498,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
499,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [10]:
#Drop rows that have more than 5 NaN numbers
df1=df.dropna(axis=0, thresh=5)
df1. reset_index (drop= True, inplace= True) 
df1

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,MFG Iowa,MFG Mexico,MFG B,MFG O.1,Quoted Ship,Revised Ship,R2 Ship,R3 Ship,Final Ship,Notes
0,2022-04-12 00:00:00,P21396,91259.0,1.0,"BAR-S ALTUS, OK",VS922 VACUUM EMULSION SYSTEM,DM,MB,FW,None,...,None,None,None,None,2022-09-23 00:00:00,2022-10-17 00:00:00,2022-10-31 00:00:00,2023-01-31 00:00:00,2023-01-31 00:00:00,None
1,2022-12-21 00:00:00,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",GUARDING PACKAGE FOR P21182,DM,N/A,FW,None,...,None,None,None,None,2023-01-31 00:00:00,None,None,None,2023-01-31 00:00:00,want to ship w/ diverter
2,2022-02-28 00:00:00,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,Steve Ward to visit
3,2022-02-28 00:00:00,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,None
4,2022-02-28 00:00:00,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,NA,None,...,None,None,None,None,2022-12-01 00:00:00,2022-12-16 00:00:00,2023-02-01 00:00:00,None,2023-02-01 00:00:00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,2020-11-11 00:00:00,P20057,85105.0,1.0,"VATAN TIJORAT, TAJIKISTAN","CCD630 COLUMN DUMPER, ITEM #8",DM,MB,KS,None,...,X,None,None,None,2021-04-30 00:00:00,TBD,None,PPD,PPD,None
299,2020-11-11 00:00:00,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","SAFELINE METAL DETECTOR, ITEM #2A (USE ON P22106)",DM,MB,DM,None,...,None,None,None,None,2021-04-30 00:00:00,TBD,None,PPD,PPD,None
300,2020-11-11 00:00:00,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","PIPING PACKAGE, ITEM #10A (partially on EGV f...",DM,MB,DM,None,...,None,None,None,None,2021-04-30 00:00:00,TBD,None,PPD,PPD,None
301,2020-11-11 00:00:00,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","CBC METAL DETECTOR BELT CONVEYOR, ITEM #2 (on ...",DM,MB,DRM,None,...,None,None,None,None,2021-04-30 00:00:00,TBD,None,PPD,PPD,None
302,2020-11-11 00:00:00,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","AR722 MULTICUT EMULSION SYSTEM, ITEM #10 (part...",DM,MB,FW,None,...,None,None,None,None,2021-04-30 00:00:00,TBD,None,PPD,PPD,None

In [11]:
#convert date columns to date time
#df['Date'] = pd.to_datetime(df['Date'])

#Issue with deleting these and putting them to the dataframe.  Maybe just rename the df? Not working as expected.
#remove stock with blanks
df1 = df1.replace("STOCK", '', regex=True)

#remove HOLD with blanks
df1 = df1.replace("HOLD", '', regex=True)

#REMOVE PPD WITH BLANKS
df1 = df1.replace("PPD", '', regex=True)

#REMOVE DATE NEEDED WITH BLANKS
df1 = df1.replace("DATE NEEDED", '', regex=True)

#REMOVE TBD WITH BLANKS
df1 = df1.replace("TBD", '', regex=True)

#print(df1)

#Change all date columns to datetime datatypes
df1['PO Date'] = pd.to_datetime(df1['PO Date'])
df1['Quoted Ship'] = pd.to_datetime(df1['Quoted Ship'])
df1['Revised Ship'] = pd.to_datetime(df1['Revised Ship'])
df1['R2 Ship'] = pd.to_datetime(df1['R2 Ship'])
df1['R3 Ship'] = pd.to_datetime(df1['R3 Ship'])
#df1['Inter-Comp Ship'] = pd.to_datetime(df1['Inter-Comp Ship'])
df1['Final Ship'] = pd.to_datetime(df1['Final Ship'])

#test for Nat number by row location
df1 = df1.dropna(subset=['PO Date'])

df1.reset_index(drop=True, inplace = True)
df1
#df1.loc[[310]]
#df1.info()

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,MFG Iowa,MFG Mexico,MFG B,MFG O.1,Quoted Ship,Revised Ship,R2 Ship,R3 Ship,Final Ship,Notes
0,2022-04-12,P21396,91259.0,1.0,"BAR-S ALTUS, OK",VS922 VACUUM EMULSION SYSTEM,DM,MB,FW,None,...,None,None,None,None,2022-09-23,2022-10-17,2022-10-31,2023-01-31,2023-01-31,None
1,2022-12-21,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",GUARDING PACKAGE FOR P21182,DM,N/A,FW,None,...,None,None,None,None,2023-01-31,NaT,NaT,NaT,2023-01-31,want to ship w/ diverter
2,2022-02-28,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01,2022-12-16,2023-02-01,NaT,2023-02-01,Steve Ward to visit
3,2022-02-28,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,None,None,None,X,2022-12-01,2022-12-16,2023-02-01,NaT,2023-02-01,None
4,2022-02-28,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,NA,None,...,None,None,None,None,2022-12-01,2022-12-16,2023-02-01,NaT,2023-02-01,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2020-11-11,P20057,85105.0,1.0,"VATAN TIJORAT, TAJIKISTAN","CCD630 COLUMN DUMPER, ITEM #8",DM,MB,KS,None,...,X,None,None,None,2021-04-30,NaT,NaT,NaT,NaT,None
267,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","SAFELINE METAL DETECTOR, ITEM #2A (USE ON P22106)",DM,MB,DM,None,...,None,None,None,None,2021-04-30,NaT,NaT,NaT,NaT,None
268,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","PIPING PACKAGE, ITEM #10A (partially on EGV f...",DM,MB,DM,None,...,None,None,None,None,2021-04-30,NaT,NaT,NaT,NaT,None
269,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","CBC METAL DETECTOR BELT CONVEYOR, ITEM #2 (on ...",DM,MB,DRM,None,...,None,None,None,None,2021-04-30,NaT,NaT,NaT,NaT,None
270,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","AR722 MULTICUT EMULSION SYSTEM, ITEM #10 (part...",DM,MB,FW,None,...,None,None,None,None,2021-04-30,NaT,NaT,NaT,NaT,None

In [12]:
#Create new columns for df1

#Add new blank columns to the list
df1['Model']=df1.Line_Item.str.split(' ').str[0] #take first characters until space to get model
df1['Model_Count']=df1.sort_values(['Project Number'], ascending=[1]).groupby('Project Number').cumcount()+1 #add something here for count of model by project Number

#convert model count to string
df1['Model_Count'] = df1['Model_Count'].apply(str)

#Create link column to be used for merging both data frames
#df1['Link']=df1['Project Number']+'-'+df1['Model']+ '-' + df1['Model_Count']

#Create a new unique link.  This one will be Project Number and Line item in order to create a unique one to delete duplicates later.  Model_count didn't work becuase
#when concacted, they missalign and don't delete all items
df1['Link']=df1['Project Number']+'-'+df1['Line_Item']

#Create Combined column which contains the project number and customer
df1['Project_Customer']=df1['Project Number']+'-'+df1['Customer']

#Create Columns for dates of importance
#setup parameters for time in weeks for different dates
kick_off_weeks = 4 #from PO receipt
Layout_Approval = 8 #from PO receipt
Design_Assigned = 10 #from PO receipt might need to base on delivery and change this
Design_Complete = 16 #from Design Assigned date/might go from delivery date
#Customer_Approval_Complete= allow two weeks from design complete
#Order_long_lead_items =?? probably after layout approval
Electric_Design_Complete = 22 #6 week after desing complete, might need to work backwords from ship date
Quote_Panels = 23 #1 week after design is complete
Panels_out_for_build = 24 #1 week after quoting
#Need to continue with this

#df['date_column']+pd.DateOffset(days=30)

#New columns to add, currently basing them off of PO Date, but might need to do this off of ship date.  Need to work on


#Project Engineer portion

df1['Kick_Off_Deadline']=df1['PO Date']+pd.DateOffset(days=30)
df1['Actual_Kick-Off_Date']=""
df1['Actual_Kick-Off_Date'] = pd.to_datetime(df1['Actual_Kick-Off_Date'])
df1['Kick-Off_Status']=""
df1['Layout_Approval_Deadline']=df1['PO Date']+pd.DateOffset(days=44) #2 weeks after kick-off
df1['Actual_Layout_Approval']=""
df1['Actual_Layout_Approval'] = pd.to_datetime(df1['Actual_Layout_Approval'])
df1['Layout_Status']=""

#Design Engineer portion
df1['Design_Deadline']=df1['PO Date']+pd.DateOffset(days=86) #6 weeks after approval (44 days)
df1['Actual_Design_Completion']=""
df1['Actual_Design_Completion'] = pd.to_datetime(df1['Actual_Design_Completion'])
df1['Design_Status']=""
df1['Customer_Approvals_Date']=df1['PO Date']+pd.DateOffset(days=100) #2 weeks from design done
df1['Actual_Customer_Approval']=""
df1['Actual_Customer_Approval'] = pd.to_datetime(df1['Actual_Customer_Approval'])
df1['Customer_Approval_Status']=""

#Order Long Lead-Items
df1['Order_Long_Lead_Items_Date']=df1['PO Date']+pd.DateOffset(days=86) #right now it is equal to design being done.  Might need to move this one
df1['Actual_Long_Lead_Date_Order']=""
df1['Actual_Long_Lead_Date_Order'] = pd.to_datetime(df1['Actual_Long_Lead_Date_Order'])
df1['Long_Lead_Order_Status']=""

#Electrical Engineer Portion
df1['Electric_Design_Deadline']=df1['PO Date']+pd.DateOffset(days=130) #right now it is 6 weeks after design complete, might need to adjust
df1['Actual_Electrical_Design_Completion']=""
df1['Actual_Electrical_Design_Completion'] = pd.to_datetime(df1['Actual_Electrical_Design_Completion'])
df1['Electrical_Design_Status']=""
df1['Panels_Quote_Deadline']=df1['PO Date']+pd.DateOffset(days=137) #right now it is 7 days after electric design deadline
df1['Panel_Built_Deadline']=df1['PO Date']+pd.DateOffset(days=193) #right now it is 8 weeks after quote or 56 days
df1['Actual_Panel_Built_Date']=""
df1['Actual_Panel_Built_Date'] = pd.to_datetime(df1['Actual_Panel_Built_Date'])
df1['Panel_Build_Status']=""

#Production Items
df1['Laser_Cut_Deadline']=df1['PO Date']+pd.DateOffset(days=193) #Need to determine best case here
df1['Actual_Laser_Date']=""
df1['Actual_Laser_Date'] = pd.to_datetime(df1['Actual_Laser_Date'])
df1['Laser_Cut_Status']=""
df1['Assembly_Deadline']=df1['PO Date']+pd.DateOffset(days=221) #Need to determine best case here
df1['Actual_Assembly_Date']=""
df1['Actual_Assembly_Date'] = pd.to_datetime(df1['Actual_Assembly_Date'])
df1['Assembly_Status']=""

#Final electrical
df1['Field_Wire_Deadline']= df1['PO Date']+pd.DateOffset(days=235) #two weeks after assembly deadline
df1['Actual_Field_Wire_Date']=""
df1['Actual_Field_Wire_Date'] = pd.to_datetime(df1['Actual_Field_Wire_Date'])
df1['Field_Wiring_Status']=""

#FAT
df1['FAT_Deadline']=df1['PO Date']+pd.DateOffset(days=242) #one week after final wiring
df1['Actual_FAT_Date']=""
df1['Actual_FAT_Date'] = pd.to_datetime(df1['Actual_FAT_Date'])
df1['FAT_Status']=""

#Add columns for outsourced items that include outsourced to, Cost Outsourced, Budgeted Cost
df1['Outsourced_To']="" #who did we outsource this to
df1['Cost_Outsourced']="" #Cost to outsource it/quoted price
df1['Budgeted']="" #This is what this item was budgeted to cost if it was built in-house

df1.info()

#Currently all of this adds up to 8 months delivery from date of PO.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 64 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PO Date                              271 non-null    datetime64[ns]
 1   Project Number                       271 non-null    object
 2   Shop Order                           49 non-null     object
 3   Qty                                  271 non-null    float64
 4   Customer                             271 non-null    object
 5   Line_Item                            271 non-null    object
 6   PE                                   271 non-null    object
 7   EE                                   247 non-null    object
 8   DE                                   189 non-null    object
 9   Mfg Dwg rec                          17 non-null     object
 10  Mfg Comp date                        33 non-null     datetime64[ns]
 11  22                                   0 non-null      object
 12  MFG Chicago                          119 non-null    object
 13  MFG Iowa                             102 non-null    object
 14  MFG Mexico                           0 non-null      object
 15  MFG B                                0 non-null      object
 16  MFG O.1                              50 non-null     object
 17  Quoted Ship                          258 non-null    datetime64[ns]
 18  Revised Ship                         183 non-null    datetime64[ns]
 19  R2 Ship                              135 non-null    datetime64[ns]
 20  R3 Ship                              68 non-null     datetime64[ns]
 21  Final Ship                           237 non-null    datetime64[ns]
 22  Notes                                21 non-null     object
 23  Model                                271 non-null    object
 24  Model_Count                          271 non-null    object
 25  Link                                 271 non-null    object
 26  Project_Customer                     271 non-null    object
 27  Kick_Off_Deadline                    271 non-null    datetime64[ns]
 28  Actual_Kick-Off_Date                 0 non-null      datetime64[ns]
 29  Kick-Off_Status                      271 non-null    object
 30  Layout_Approval_Deadline             271 non-null    datetime64[ns]
 31  Actual_Layout_Approval               0 non-null      datetime64[ns]
 32  Layout_Status                        271 non-null    object
 33  Design_Deadline                      271 non-null    datetime64[ns]
 34  Actual_Design_Completion             0 non-null      datetime64[ns]
 35  Design_Status                        271 non-null    object
 36  Customer_Approvals_Date              271 non-null    datetime64[ns]
 37  Actual_Customer_Approval             0 non-null      datetime64[ns]
 38  Customer_Approval_Status             271 non-null    object
 39  Order_Long_Lead_Items_Date           271 non-null    datetime64[ns]
 40  Actual_Long_Lead_Date_Order          0 non-null      datetime64[ns]
 41  Long_Lead_Order_Status               271 non-null    object
 42  Electric_Design_Deadline             271 non-null    datetime64[ns]
 43  Actual_Electrical_Design_Completion  0 non-null      datetime64[ns]
 44  Electrical_Design_Status             271 non-null    object
 45  Panels_Quote_Deadline                271 non-null    datetime64[ns]
 46  Panel_Built_Deadline                 271 non-null    datetime64[ns]
 47  Actual_Panel_Built_Date              0 non-null      datetime64[ns]
 48  Panel_Build_Status                   271 non-null    object
 49  Laser_Cut_Deadline                   271 non-null    datetime64[ns]
 50  Actual_Laser_Date                    0 non-null      datetime64[ns]
 51  Laser_Cut_Status                     271 non-null    object
 52  Assembly_Deadline                    271 non-null    datetime64[ns]
 53  Actual_Assembly_Date                 0 non-null      datetime64[ns]
 54  Assembly_Status                      271 non-null    object
 55  Field_Wire_Deadline                  271 non-null    datetime64[ns]
 56  Actual_Field_Wire_Date               0 non-null      datetime64[ns]
 57  Field_Wiring_Status                  271 non-null    object
 58  FAT_Deadline                         271 non-null    datetime64[ns]
 59  Actual_FAT_Date                      0 non-null      datetime64[ns]
 60  FAT_Status                           271 non-null    object
 61  Outsourced_To                        271 non-null    object
 62  Cost_Outsourced                      271 non-null    object
 63  Budgeted                             271 non-null    object
dtypes: datetime64[ns](30), float64(1), object(33)
memory usage: 135.6+ KB

In [13]:
#Create a function that takes the five manufacturing locations and makes them one column with the manufacturing location



def conditions(mfgc, mfgi, mfgm, mfgb, mfgd):
    if mfgc == "X":
        return "EGV"
    elif mfgi == "X":
        return "Algona"
    elif mfgm == "X":
        return "Mexico"
    elif mfgb == "X":
        return "Brazil"
    elif mfgd == "X":
        return "Denmark"
    else:
        return "WTF"

In [14]:
#Call conditions function created above to fill Manufactured column with manufacturing location
df1['Manufactured']=""
df1['Manufactured'] = df1.apply(lambda x: conditions(x['MFG Chicago'], x['MFG Iowa'], x['MFG Mexico'], x['MFG B'], x['MFG O.1']), axis=1)
df1
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 65 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PO Date                              271 non-null    datetime64[ns]
 1   Project Number                       271 non-null    object
 2   Shop Order                           49 non-null     object
 3   Qty                                  271 non-null    float64
 4   Customer                             271 non-null    object
 5   Line_Item                            271 non-null    object
 6   PE                                   271 non-null    object
 7   EE                                   247 non-null    object
 8   DE                                   189 non-null    object
 9   Mfg Dwg rec                          17 non-null     object
 10  Mfg Comp date                        33 non-null     datetime64[ns]
 11  22                                   0 non-null      object
 12  MFG Chicago                          119 non-null    object
 13  MFG Iowa                             102 non-null    object
 14  MFG Mexico                           0 non-null      object
 15  MFG B                                0 non-null      object
 16  MFG O.1                              50 non-null     object
 17  Quoted Ship                          258 non-null    datetime64[ns]
 18  Revised Ship                         183 non-null    datetime64[ns]
 19  R2 Ship                              135 non-null    datetime64[ns]
 20  R3 Ship                              68 non-null     datetime64[ns]
 21  Final Ship                           237 non-null    datetime64[ns]
 22  Notes                                21 non-null     object
 23  Model                                271 non-null    object
 24  Model_Count                          271 non-null    object
 25  Link                                 271 non-null    object
 26  Project_Customer                     271 non-null    object
 27  Kick_Off_Deadline                    271 non-null    datetime64[ns]
 28  Actual_Kick-Off_Date                 0 non-null      datetime64[ns]
 29  Kick-Off_Status                      271 non-null    object
 30  Layout_Approval_Deadline             271 non-null    datetime64[ns]
 31  Actual_Layout_Approval               0 non-null      datetime64[ns]
 32  Layout_Status                        271 non-null    object
 33  Design_Deadline                      271 non-null    datetime64[ns]
 34  Actual_Design_Completion             0 non-null      datetime64[ns]
 35  Design_Status                        271 non-null    object
 36  Customer_Approvals_Date              271 non-null    datetime64[ns]
 37  Actual_Customer_Approval             0 non-null      datetime64[ns]
 38  Customer_Approval_Status             271 non-null    object
 39  Order_Long_Lead_Items_Date           271 non-null    datetime64[ns]
 40  Actual_Long_Lead_Date_Order          0 non-null      datetime64[ns]
 41  Long_Lead_Order_Status               271 non-null    object
 42  Electric_Design_Deadline             271 non-null    datetime64[ns]
 43  Actual_Electrical_Design_Completion  0 non-null      datetime64[ns]
 44  Electrical_Design_Status             271 non-null    object
 45  Panels_Quote_Deadline                271 non-null    datetime64[ns]
 46  Panel_Built_Deadline                 271 non-null    datetime64[ns]
 47  Actual_Panel_Built_Date              0 non-null      datetime64[ns]
 48  Panel_Build_Status                   271 non-null    object
 49  Laser_Cut_Deadline                   271 non-null    datetime64[ns]
 50  Actual_Laser_Date                    0 non-null      datetime64[ns]
 51  Laser_Cut_Status                     271 non-null    object
 52  Assembly_Deadline                    271 non-null    datetime64[ns]
 53  Actual_Assembly_Date                 0 non-null      datetime64[ns]
 54  Assembly_Status                      271 non-null    object
 55  Field_Wire_Deadline                  271 non-null    datetime64[ns]
 56  Actual_Field_Wire_Date               0 non-null      datetime64[ns]
 57  Field_Wiring_Status                  271 non-null    object
 58  FAT_Deadline                         271 non-null    datetime64[ns]
 59  Actual_FAT_Date                      0 non-null      datetime64[ns]
 60  FAT_Status                           271 non-null    object
 61  Outsourced_To                        271 non-null    object
 62  Cost_Outsourced                      271 non-null    object
 63  Budgeted                             271 non-null    object
 64  Manufactured                         271 non-null    object
dtypes: datetime64[ns](30), float64(1), object(34)
memory usage: 137.7+ KB

In [15]:
#Delete the 5 manfucturing columns

#df10=df1
df1 = df1.drop(['MFG Chicago', 'MFG Iowa', 'MFG Mexico', 'MFG B', 'MFG O.1'], axis=1)
df1

df1 = df1.drop(df1.columns[11],axis = 1)
df1

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,Field_Wire_Deadline,Actual_Field_Wire_Date,Field_Wiring_Status,FAT_Deadline,Actual_FAT_Date,FAT_Status,Outsourced_To,Cost_Outsourced,Budgeted,Manufactured
0,2022-04-12,P21396,91259.0,1.0,"BAR-S ALTUS, OK",VS922 VACUUM EMULSION SYSTEM,DM,MB,FW,None,...,2022-12-03,NaT,,2022-12-10,NaT,,,,,EGV
1,2022-12-21,P22316,None,1.0,"CARGILL FOODS COLUMBUS, NE",GUARDING PACKAGE FOR P21182,DM,N/A,FW,None,...,2023-08-13,NaT,,2023-08-20,NaT,,,,,EGV
2,2022-02-28,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,2022-10-21,NaT,,2022-10-28,NaT,,,,,Denmark
3,2022-02-28,P22019,BIOFAB,1.0,"MONOGRAM FOODS MARTINSVILLE, VA","CMB8000 PADDLE MIXER/BLENDER W/ WATER METER, 8...",DM,MB,FG,None,...,2022-10-21,NaT,,2022-10-28,NaT,,,,,Denmark
4,2022-02-28,P22019,None,1.0,"MONOGRAM FOODS MARTINSVILLE, VA",EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #39A),DM,MB,NA,None,...,2022-10-21,NaT,,2022-10-28,NaT,,,,,EGV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2020-11-11,P20057,85105.0,1.0,"VATAN TIJORAT, TAJIKISTAN","CCD630 COLUMN DUMPER, ITEM #8",DM,MB,KS,None,...,2021-07-04,NaT,,2021-07-11,NaT,,,,,Algona
267,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","SAFELINE METAL DETECTOR, ITEM #2A (USE ON P22106)",DM,MB,DM,None,...,2021-07-04,NaT,,2021-07-11,NaT,,,,,EGV
268,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","PIPING PACKAGE, ITEM #10A (partially on EGV f...",DM,MB,DM,None,...,2021-07-04,NaT,,2021-07-11,NaT,,,,,EGV
269,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","CBC METAL DETECTOR BELT CONVEYOR, ITEM #2 (on ...",DM,MB,DRM,None,...,2021-07-04,NaT,,2021-07-11,NaT,,,,,EGV
270,2020-11-11,P20057,None,1.0,"VATAN TIJORAT, TAJIKISTAN","AR722 MULTICUT EMULSION SYSTEM, ITEM #10 (part...",DM,MB,FW,None,...,2021-07-04,NaT,,2021-07-11,NaT,,,,,EGV

In [16]:

#app=xw.App()
wb = xw.Book("C://Users//abasalay//OneDrive - Middleby//test1.xlsx")
#ws = wb.sheets["Sheet1"]

In [17]:
#Add df1 to sheet for a test

#Create a sheet name One

#wb.sheets.add('One')

#wsone= wb.sheets["One"]
#wsone["A1"].options(pd.DataFrame, header=1, index=True, expand='table').value = df1

In [18]:
#Rename Sheet and save as "TestTracker1"

path="C://Users//abasalay//OneDrive - Middleby//test1.xlsx"

dftemp = pd.read_excel(path, sheet_name='TestTracker1')

In [19]:
#drop first three rows of dftemp
#dftemp.drop(index=dftemp.index[0:3], axis=0, inplace=True)

#Change Data types to match that of df1
#All items for Objects
dftemp['Kick-Off_Status'] = dftemp['Kick-Off_Status'].apply(str)
dftemp['Layout_Status'] = dftemp['Layout_Status'].apply(str)
dftemp['Design_Status'] = dftemp['Design_Status'].apply(str)
dftemp['Customer_Approval_Status'] = dftemp['Customer_Approval_Status'].apply(str)
dftemp['Layout_Status'] = dftemp['Layout_Status'].apply(str)
dftemp['Long_Lead_Order_Status'] = dftemp['Long_Lead_Order_Status'].apply(str)
dftemp['Electrical_Design_Status'] = dftemp['Electrical_Design_Status'].apply(str)
dftemp['Panel_Build_Status'] = dftemp['Panel_Build_Status'].apply(str)
dftemp['Laser_Cut_Status'] = dftemp['Laser_Cut_Status'].apply(str)
dftemp['Assembly_Status'] = dftemp['Assembly_Status'].apply(str)
dftemp['Field_Wiring_Status'] = dftemp['Field_Wiring_Status'].apply(str)
dftemp['FAT_Status'] = dftemp['FAT_Status'].apply(str)

#All items for datetime
dftemp['Actual_Kick-Off_Date'] = pd.to_datetime(dftemp['Actual_Kick-Off_Date'])
dftemp['Actual_Layout_Approval'] = pd.to_datetime(dftemp['Actual_Layout_Approval'])
dftemp['Actual_Design_Completion'] = pd.to_datetime(dftemp['Actual_Design_Completion'])
dftemp['Actual_Customer_Approval'] = pd.to_datetime(dftemp['Actual_Customer_Approval'])
dftemp['Actual_Long_Lead_Date_Order'] = pd.to_datetime(dftemp['Actual_Long_Lead_Date_Order'])
dftemp['Actual_Electrical_Design_Completion'] = pd.to_datetime(dftemp['Actual_Electrical_Design_Completion'])
dftemp['Actual_Panel_Built_Date'] = pd.to_datetime(dftemp['Actual_Panel_Built_Date'])
dftemp['Actual_Laser_Date'] = pd.to_datetime(dftemp['Actual_Laser_Date'])
dftemp['Actual_Assembly_Date'] = pd.to_datetime(dftemp['Actual_Assembly_Date'])
dftemp['Actual_Field_Wire_Date'] = pd.to_datetime(dftemp['Actual_Field_Wire_Date'])
dftemp['Actual_FAT_Date'] = pd.to_datetime(dftemp['Actual_FAT_Date'])

dftemp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 59 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PO Date                              372 non-null    datetime64[ns]
 1   Project Number                       372 non-null    object
 2   Shop Order                           65 non-null     object
 3   Qty                                  372 non-null    int64
 4   Customer                             372 non-null    object
 5   Line_Item                            372 non-null    object
 6   PE                                   372 non-null    object
 7   EE                                   290 non-null    object
 8   DE                                   159 non-null    object
 9   Mfg Dwg rec                          30 non-null     datetime64[ns]
 10  Mfg Comp date                        43 non-null     datetime64[ns]
 11  Quoted Ship                          344 non-null    datetime64[ns]
 12  Revised Ship                         263 non-null    datetime64[ns]
 13  R2 Ship                              167 non-null    datetime64[ns]
 14  R3 Ship                              110 non-null    datetime64[ns]
 15  Final Ship                           334 non-null    datetime64[ns]
 16  Notes                                83 non-null     object
 17  Model                                372 non-null    object
 18  Model_Count                          372 non-null    int64
 19  Link                                 372 non-null    object
 20  Project_Customer                     372 non-null    object
 21  Kick_Off_Deadline                    372 non-null    datetime64[ns]
 22  Actual_Kick-Off_Date                 22 non-null     datetime64[ns]
 23  Kick-Off_Status                      372 non-null    object
 24  Layout_Approval_Deadline             372 non-null    datetime64[ns]
 25  Actual_Layout_Approval               0 non-null      datetime64[ns]
 26  Layout_Status                        372 non-null    object
 27  Design_Deadline                      372 non-null    datetime64[ns]
 28  Actual_Design_Completion             40 non-null     datetime64[ns]
 29  Design_Status                        372 non-null    object
 30  Customer_Approvals_Date              372 non-null    datetime64[ns]
 31  Actual_Customer_Approval             0 non-null      datetime64[ns]
 32  Customer_Approval_Status             372 non-null    object
 33  Order_Long_Lead_Items_Date           372 non-null    datetime64[ns]
 34  Actual_Long_Lead_Date_Order          0 non-null      datetime64[ns]
 35  Long_Lead_Order_Status               372 non-null    object
 36  Electric_Design_Deadline             372 non-null    datetime64[ns]
 37  Actual_Electrical_Design_Completion  1 non-null      datetime64[ns]
 38  Electrical_Design_Status             372 non-null    object
 39  Panels_Quote_Deadline                372 non-null    datetime64[ns]
 40  Panel_Built_Deadline                 372 non-null    datetime64[ns]
 41  Actual_Panel_Built_Date              1 non-null      datetime64[ns]
 42  Panel_Build_Status                   372 non-null    object
 43  Laser_Cut_Deadline                   372 non-null    datetime64[ns]
 44  Actual_Laser_Date                    23 non-null     datetime64[ns]
 45  Laser_Cut_Status                     372 non-null    object
 46  Assembly_Deadline                    372 non-null    datetime64[ns]
 47  Actual_Assembly_Date                 5 non-null      datetime64[ns]
 48  Assembly_Status                      372 non-null    object
 49  Field_Wire_Deadline                  372 non-null    datetime64[ns]
 50  Actual_Field_Wire_Date               0 non-null      datetime64[ns]
 51  Field_Wiring_Status                  372 non-null    object
 52  FAT_Deadline                         372 non-null    datetime64[ns]
 53  Actual_FAT_Date                      41 non-null     datetime64[ns]
 54  FAT_Status                           372 non-null    object
 55  Outsourced_To                        14 non-null     object
 56  Cost_Outsourced                      10 non-null     float64
 57  Budgeted                             2 non-null      float64
 58  Manufactured                         372 non-null    object
dtypes: datetime64[ns](31), float64(2), int64(2), object(24)
memory usage: 171.6+ KB

In [20]:
#Drop 1st column on dftemp, which is the index
#dftemp=dftemp.drop(dftemp.iloc[:,0:1], axis=1)

#Change all dftemp items to object in order to match df1
#dftemp = dftemp.astype(str)
df1.info()
dftemp.info()
dftemp
#df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 59 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PO Date                              271 non-null    datetime64[ns]
 1   Project Number                       271 non-null    object
 2   Shop Order                           49 non-null     object
 3   Qty                                  271 non-null    float64
 4   Customer                             271 non-null    object
 5   Line_Item                            271 non-null    object
 6   PE                                   271 non-null    object
 7   EE                                   247 non-null    object
 8   DE                                   189 non-null    object
 9   Mfg Dwg rec                          17 non-null     object
 10  Mfg Comp date                        33 non-null     datetime64[ns]
 11  Quoted Ship                          258 non-null    datetime64[ns]
 12  Revised Ship                         183 non-null    datetime64[ns]
 13  R2 Ship                              135 non-null    datetime64[ns]
 14  R3 Ship                              68 non-null     datetime64[ns]
 15  Final Ship                           237 non-null    datetime64[ns]
 16  Notes                                21 non-null     object
 17  Model                                271 non-null    object
 18  Model_Count                          271 non-null    object
 19  Link                                 271 non-null    object
 20  Project_Customer                     271 non-null    object
 21  Kick_Off_Deadline                    271 non-null    datetime64[ns]
 22  Actual_Kick-Off_Date                 0 non-null      datetime64[ns]
 23  Kick-Off_Status                      271 non-null    object
 24  Layout_Approval_Deadline             271 non-null    datetime64[ns]
 25  Actual_Layout_Approval               0 non-null      datetime64[ns]
 26  Layout_Status                        271 non-null    object
 27  Design_Deadline                      271 non-null    datetime64[ns]
 28  Actual_Design_Completion             0 non-null      datetime64[ns]
 29  Design_Status                        271 non-null    object
 30  Customer_Approvals_Date              271 non-null    datetime64[ns]
 31  Actual_Customer_Approval             0 non-null      datetime64[ns]
 32  Customer_Approval_Status             271 non-null    object
 33  Order_Long_Lead_Items_Date           271 non-null    datetime64[ns]
 34  Actual_Long_Lead_Date_Order          0 non-null      datetime64[ns]
 35  Long_Lead_Order_Status               271 non-null    object
 36  Electric_Design_Deadline             271 non-null    datetime64[ns]
 37  Actual_Electrical_Design_Completion  0 non-null      datetime64[ns]
 38  Electrical_Design_Status             271 non-null    object
 39  Panels_Quote_Deadline                271 non-null    datetime64[ns]
 40  Panel_Built_Deadline                 271 non-null    datetime64[ns]
 41  Actual_Panel_Built_Date              0 non-null      datetime64[ns]
 42  Panel_Build_Status                   271 non-null    object
 43  Laser_Cut_Deadline                   271 non-null    datetime64[ns]
 44  Actual_Laser_Date                    0 non-null      datetime64[ns]
 45  Laser_Cut_Status                     271 non-null    object
 46  Assembly_Deadline                    271 non-null    datetime64[ns]
 47  Actual_Assembly_Date                 0 non-null      datetime64[ns]
 48  Assembly_Status                      271 non-null    object
 49  Field_Wire_Deadline                  271 non-null    datetime64[ns]
 50  Actual_Field_Wire_Date               0 non-null      datetime64[ns]
 51  Field_Wiring_Status                  271 non-null    object
 52  FAT_Deadline                         271 non-null    datetime64[ns]
 53  Actual_FAT_Date                      0 non-null      datetime64[ns]
 54  FAT_Status                           271 non-null    object
 55  Outsourced_To                        271 non-null    object
 56  Cost_Outsourced                      271 non-null    object
 57  Budgeted                             271 non-null    object
 58  Manufactured                         271 non-null    object
dtypes: datetime64[ns](30), float64(1), object(28)
memory usage: 125.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 59 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PO Date                              372 non-null    datetime64[ns]
 1   Project Number                       372 non-null    object
 2   Shop Order                           65 non-null     object
 3   Qty                                  372 non-null    int64
 4   Customer                             372 non-null    object
 5   Line_Item                            372 non-null    object
 6   PE                                   372 non-null    object
 7   EE                                   290 non-null    object
 8   DE                                   159 non-null    object
 9   Mfg Dwg rec                          30 non-null     datetime64[ns]
 10  Mfg Comp date                        43 non-null     datetime64[ns]
 11  Quoted Ship                          344 non-null    datetime64[ns]
 12  Revised Ship                         263 non-null    datetime64[ns]
 13  R2 Ship                              167 non-null    datetime64[ns]
 14  R3 Ship                              110 non-null    datetime64[ns]
 15  Final Ship                           334 non-null    datetime64[ns]
 16  Notes                                83 non-null     object
 17  Model                                372 non-null    object
 18  Model_Count                          372 non-null    int64
 19  Link                                 372 non-null    object
 20  Project_Customer                     372 non-null    object
 21  Kick_Off_Deadline                    372 non-null    datetime64[ns]
 22  Actual_Kick-Off_Date                 22 non-null     datetime64[ns]
 23  Kick-Off_Status                      372 non-null    object
 24  Layout_Approval_Deadline             372 non-null    datetime64[ns]
 25  Actual_Layout_Approval               0 non-null      datetime64[ns]
 26  Layout_Status                        372 non-null    object
 27  Design_Deadline                      372 non-null    datetime64[ns]
 28  Actual_Design_Completion             40 non-null     datetime64[ns]
 29  Design_Status                        372 non-null    object
 30  Customer_Approvals_Date              372 non-null    datetime64[ns]
 31  Actual_Customer_Approval             0 non-null      datetime64[ns]
 32  Customer_Approval_Status             372 non-null    object
 33  Order_Long_Lead_Items_Date           372 non-null    datetime64[ns]
 34  Actual_Long_Lead_Date_Order          0 non-null      datetime64[ns]
 35  Long_Lead_Order_Status               372 non-null    object
 36  Electric_Design_Deadline             372 non-null    datetime64[ns]
 37  Actual_Electrical_Design_Completion  1 non-null      datetime64[ns]
 38  Electrical_Design_Status             372 non-null    object
 39  Panels_Quote_Deadline                372 non-null    datetime64[ns]
 40  Panel_Built_Deadline                 372 non-null    datetime64[ns]
 41  Actual_Panel_Built_Date              1 non-null      datetime64[ns]
 42  Panel_Build_Status                   372 non-null    object
 43  Laser_Cut_Deadline                   372 non-null    datetime64[ns]
 44  Actual_Laser_Date                    23 non-null     datetime64[ns]
 45  Laser_Cut_Status                     372 non-null    object
 46  Assembly_Deadline                    372 non-null    datetime64[ns]
 47  Actual_Assembly_Date                 5 non-null      datetime64[ns]
 48  Assembly_Status                      372 non-null    object
 49  Field_Wire_Deadline                  372 non-null    datetime64[ns]
 50  Actual_Field_Wire_Date               0 non-null      datetime64[ns]
 51  Field_Wiring_Status                  372 non-null    object
 52  FAT_Deadline                         372 non-null    datetime64[ns]
 53  Actual_FAT_Date                      41 non-null     datetime64[ns]
 54  FAT_Status                           372 non-null    object
 55  Outsourced_To                        14 non-null     object
 56  Cost_Outsourced                      10 non-null     float64
 57  Budgeted                             2 non-null      float64
 58  Manufactured                         372 non-null    object
dtypes: datetime64[ns](31), float64(2), int64(2), object(24)
memory usage: 171.6+ KB

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,Field_Wire_Deadline,Actual_Field_Wire_Date,Field_Wiring_Status,FAT_Deadline,Actual_FAT_Date,FAT_Status,Outsourced_To,Cost_Outsourced,Budgeted,Manufactured
0,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT EMULSION SYSTEM (ITEM #2),DM,MAR,FW,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
1,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA","CSLH3500 HORIZONTAL SCREW LOADER WITH PUMP, 35...",DM,MAR,MARIO,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,Mexico
2,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT SANITATION PARTS CART,DM,MAR,NaN,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
3,2022-06-15,P22090,92009,1,"SEABOARD TRIUMPH FOODS ST. JOSEPH, MO",CCD630-P PORTABLE COLUMN DUMPER W/ EXTENDED CHUTE,DM,VM,NaN,NaT,...,2023-02-05,NaT,Complete,2023-02-12,NaT,Complete,NaN,NaN,NaN,Algona
4,2022-09-07,P22185,92788,1,"SMITHFIELD FOODS - (CARANDO) SPRINGFIELD, MA",AUTOBAGGER INFEED KNOCK DOWN ASSEMBLIES,DM,NaN,NaN,NaT,...,2023-04-30,NaT,nan,2023-05-07,NaT,Complete,NaN,NaN,NaN,Algona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,2023-01-17,P21042,NaN,1,"OSI (Oakland Foods) - OAKLAND, IA",TRANSFER WEIGH BELT CONVEYOR (ITEM #5)-EAGLESTONE,TM,NaN,Eagle,NaT,...,2023-09-09,NaT,nan,2023-09-16,NaT,nan,NaN,NaN,NaN,Denmark
368,2023-01-17,P21042,NaN,1,"OSI (Oakland Foods) - OAKLAND, IA",TRANSFER WEIGH BELT CONVEYOR (ITEM #6)-EAGLESTONE,TM,NaN,eagle,NaT,...,2023-09-09,NaT,nan,2023-09-16,NaT,nan,NaN,NaN,NaN,Denmark
369,2023-01-17,P21042,NaN,1,"OSI (Oakland Foods) - OAKLAND, IA",DANFOTECH TYPE 8-35 LOG PRESS W/ ELEVATING BAS...,TM,NaN,NaN,NaT,...,2023-09-09,NaT,nan,2023-09-16,NaT,nan,NaN,NaN,NaN,Denmark
370,2023-01-17,P21042,NaN,1,"OSI (Oakland Foods) - OAKLAND, IA",DANFOTECH TYPE 8-35 LOG PRESS W/ ELEVATING BAS...,TM,NaN,NaN,NaT,...,2023-09-09,NaT,nan,2023-09-16,NaT,nan,NaN,NaN,NaN,Denmark
371,2023-01-17,P21042,NaN,1,"OSI (Oakland Foods) - OAKLAND, IA",CENTRAL CONTROL SYSTEM,TM,NaN,NaN,NaT,...,2023-09-09,NaT,nan,2023-09-16,NaT,nan,NaN,NaN,NaN,Denmark

In [21]:
#concat df1 and dftemp to make the new data frame

print(df1.index)
print(dftemp.index)
df_final = pd.concat([dftemp, df1]) #.reset_index()
df_final
df_final=df_final.reset_index()
df_final

#dftemp=dftemp.drop(dftemp.iloc[:,0:1], axis=1)
df_final=df_final.drop(df_final.iloc[:,0:1], axis=1)
df_final

df_final1=df_final.drop_duplicates(subset=['Link'])
df_final1

df_final2=df_final1.reset_index()
df_final2=df_final2.drop(df_final2.iloc[:,0:1], axis=1)
df_final2

#Replace nan numbers with blanks
df_final3 =df_final2.replace("nan", '', regex=True)
df_final3

#df_list = df_list.reset_index(drop=True)

RangeIndex(start=0, stop=271, step=1)
RangeIndex(start=0, stop=372, step=1)

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,Field_Wire_Deadline,Actual_Field_Wire_Date,Field_Wiring_Status,FAT_Deadline,Actual_FAT_Date,FAT_Status,Outsourced_To,Cost_Outsourced,Budgeted,Manufactured
0,2022-02-11,P21235,NaN,1.0,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT EMULSION SYSTEM (ITEM #2),DM,MAR,FW,NaT,...,2022-10-04,NaT,,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
1,2022-02-11,P21235,NaN,1.0,"EMPACADORA TOLEDO, GUATEMALA","CSLH3500 HORIZONTAL SCREW LOADER WITH PUMP, 35...",DM,MAR,MARIO,NaT,...,2022-10-04,NaT,,2022-10-11,NaT,Complete,NaN,NaN,NaN,Mexico
2,2022-02-11,P21235,NaN,1.0,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT SANITATION PARTS CART,DM,MAR,NaN,NaT,...,2022-10-04,NaT,,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
3,2022-06-15,P22090,92009,1.0,"SEABOARD TRIUMPH FOODS ST. JOSEPH, MO",CCD630-P PORTABLE COLUMN DUMPER W/ EXTENDED CHUTE,DM,VM,NaN,NaT,...,2023-02-05,NaT,Complete,2023-02-12,NaT,Complete,NaN,NaN,NaN,Algona
4,2022-09-07,P22185,92788,1.0,"SMITHFIELD FOODS - (CARANDO) SPRINGFIELD, MA",AUTOBAGGER INFEED KNOCK DOWN ASSEMBLIES,DM,NaN,NaN,NaT,...,2023-04-30,NaT,,2023-05-07,NaT,Complete,NaN,NaN,NaN,Algona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,2023-01-17,P21042,NaN,1.0,"OSI (Oakland Foods) - OAKLAND, IA",TRANSFER WEIGH BELT CONVEYOR (ITEM #6)-EAGLESTONE,TM,NaN,eagle,NaT,...,2023-09-09,NaT,,2023-09-16,NaT,,NaN,NaN,NaN,Denmark
369,2023-01-17,P21042,NaN,1.0,"OSI (Oakland Foods) - OAKLAND, IA",DANFOTECH TYPE 8-35 LOG PRESS W/ ELEVATING BAS...,TM,NaN,NaN,NaT,...,2023-09-09,NaT,,2023-09-16,NaT,,NaN,NaN,NaN,Denmark
370,2023-01-17,P21042,NaN,1.0,"OSI (Oakland Foods) - OAKLAND, IA",DANFOTECH TYPE 8-35 LOG PRESS W/ ELEVATING BAS...,TM,NaN,NaN,NaT,...,2023-09-09,NaT,,2023-09-16,NaT,,NaN,NaN,NaN,Denmark
371,2023-01-17,P21042,NaN,1.0,"OSI (Oakland Foods) - OAKLAND, IA",CENTRAL CONTROL SYSTEM,TM,NaN,NaN,NaT,...,2023-09-09,NaT,,2023-09-16,NaT,,NaN,NaN,NaN,Denmark
372,2023-01-20,P23026,NaN,1.0,OTABEK LLC - UZBEKISTAN,DANFOTECH TYPE 8S SERVO MEAT PRESS WITH CONTROLS,DFT,N/A,None,NaT,...,2023-09-12,NaT,,2023-09-19,NaT,,,,,Denmark

In [22]:
# Merge the DataFrames
#This can be removed as I'm not using it
df_merged = pd.merge(dftemp, df1, how='inner', left_index=True,
                     right_index=True, suffixes=('', '_remove'))

print(df_merged)

# remove the duplicate columns
df_merged.drop([i for i in df_merged.columns if 'remove' in i],
               axis=1, inplace=True)
  
df_merged

       PO Date Project Number Shop Order  Qty  \
0   2022-02-11         P21235        NaN    1
1   2022-02-11         P21235        NaN    1
2   2022-02-11         P21235        NaN    1
3   2022-06-15         P22090      92009    1
4   2022-09-07         P22185      92788    1
..         ...            ...        ...  ...
266 2022-06-28         P21411        NaN    1
267 2022-06-28         P21411        NaN    1
268 2022-06-28         P21411        NaN    1
269 2022-06-28         P21411        NaN    1
270 2022-06-28         P21411        NaN    1

                                         Customer  \
0                    EMPACADORA TOLEDO, GUATEMALA
1                    EMPACADORA TOLEDO, GUATEMALA
2                    EMPACADORA TOLEDO, GUATEMALA
3         SEABOARD TRIUMPH FOODS  ST.  JOSEPH, MO
4    SMITHFIELD FOODS - (CARANDO) SPRINGFIELD, MA
..                                            ...
266                CONAGRA FOODS FAYETTEVILLE, AR
267                CONAGRA FOODS FAYETTEVILLE, AR
268                CONAGRA FOODS FAYETTEVILLE, AR
269                CONAGRA FOODS FAYETTEVILLE, AR
270                CONAGRA FOODS FAYETTEVILLE, AR

                                             Line_Item  PE   EE     DE  \
0           CPF7-QC QUAD CUT EMULSION SYSTEM (ITEM #2)  DM  MAR     FW
1    CSLH3500 HORIZONTAL SCREW LOADER WITH PUMP, 35...  DM  MAR  MARIO
2               CPF7-QC QUAD CUT SANITATION PARTS CART  DM  MAR    NaN
3    CCD630-P PORTABLE COLUMN DUMPER W/ EXTENDED CHUTE  DM   VM    NaN
4              AUTOBAGGER INFEED KNOCK DOWN ASSEMBLIES  DM  NaN    NaN
..                                                 ...  ..  ...    ...
266        EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #2A)  DM  MAR    NaN
267               CBC TRANSFER BELT CONVEYOR (ITEM #3)  DM  MAR    NaN
268        CWT FROZEN BLOCK UNWRAPPING TABLE (ITEM #4)  DM  MAR    NaN
269               CBC TRANSFER BELT CONVEYOR (ITEM #5)  DM  MAR    NaN
270      CBC-MD METAL DETECTOR BELT CONVEYOR (ITEM #6)  DM  MAR    NaN

    Mfg Dwg rec  ... Field_Wire_Deadline_remove Actual_Field_Wire_Date_remove  \
0           NaT  ...                 2022-12-03                           NaT
1           NaT  ...                 2023-08-13                           NaT
2           NaT  ...                 2022-10-21                           NaT
3           NaT  ...                 2022-10-21                           NaT
4           NaT  ...                 2022-10-21                           NaT
..          ...  ...                        ...                           ...
266         NaT  ...                 2021-07-04                           NaT
267         NaT  ...                 2021-07-04                           NaT
268         NaT  ...                 2021-07-04                           NaT
269         NaT  ...                 2021-07-04                           NaT
270         NaT  ...                 2021-07-04                           NaT

    Field_Wiring_Status_remove FAT_Deadline_remove Actual_FAT_Date_remove  \
0                                       2022-12-10                    NaT
1                                       2023-08-20                    NaT
2                                       2022-10-28                    NaT
3                                       2022-10-28                    NaT
4                                       2022-10-28                    NaT
..                         ...                 ...                    ...
266                                     2021-07-11                    NaT
267                                     2021-07-11                    NaT
268                                     2021-07-11                    NaT
269                                     2021-07-11                    NaT
270                                     2021-07-11                    NaT

    FAT_Status_remove Outsourced_To_remove Cost_Outsourced_remove  \
0
1
2
3
4
..                ...                  ...                    ...
266
267
268
269
270

     Budgeted_remove Manufactured_remove
0                                    EGV
1                                    EGV
2                                Denmark
3                                Denmark
4                                    EGV
..               ...                 ...
266                               Algona
267                                  EGV
268                                  EGV
269                                  EGV
270                                  EGV

[271 rows x 118 columns]

,PO Date,Project Number,Shop Order,Qty,Customer,Line_Item,PE,EE,DE,Mfg Dwg rec,...,Field_Wire_Deadline,Actual_Field_Wire_Date,Field_Wiring_Status,FAT_Deadline,Actual_FAT_Date,FAT_Status,Outsourced_To,Cost_Outsourced,Budgeted,Manufactured
0,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT EMULSION SYSTEM (ITEM #2),DM,MAR,FW,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
1,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA","CSLH3500 HORIZONTAL SCREW LOADER WITH PUMP, 35...",DM,MAR,MARIO,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,Mexico
2,2022-02-11,P21235,NaN,1,"EMPACADORA TOLEDO, GUATEMALA",CPF7-QC QUAD CUT SANITATION PARTS CART,DM,MAR,NaN,NaT,...,2022-10-04,NaT,nan,2022-10-11,NaT,Complete,NaN,NaN,NaN,EGV
3,2022-06-15,P22090,92009,1,"SEABOARD TRIUMPH FOODS ST. JOSEPH, MO",CCD630-P PORTABLE COLUMN DUMPER W/ EXTENDED CHUTE,DM,VM,NaN,NaT,...,2023-02-05,NaT,Complete,2023-02-12,NaT,Complete,NaN,NaN,NaN,Algona
4,2022-09-07,P22185,92788,1,"SMITHFIELD FOODS - (CARANDO) SPRINGFIELD, MA",AUTOBAGGER INFEED KNOCK DOWN ASSEMBLIES,DM,NaN,NaN,NaT,...,2023-04-30,NaT,nan,2023-05-07,NaT,Complete,NaN,NaN,NaN,Algona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2022-06-28,P21411,NaN,1,"CONAGRA FOODS FAYETTEVILLE, AR",EMERY HYTRONIC LOAD CELL PACKAGE (ITEM #2A),DM,MAR,NaN,NaT,...,2023-02-18,NaT,nan,2023-02-25,NaT,nan,NaN,NaN,NaN,EGV
267,2022-06-28,P21411,NaN,1,"CONAGRA FOODS FAYETTEVILLE, AR",CBC TRANSFER BELT CONVEYOR (ITEM #3),DM,MAR,NaN,NaT,...,2023-02-18,NaT,nan,2023-02-25,NaT,nan,NaN,NaN,NaN,EGV
268,2022-06-28,P21411,NaN,1,"CONAGRA FOODS FAYETTEVILLE, AR",CWT FROZEN BLOCK UNWRAPPING TABLE (ITEM #4),DM,MAR,NaN,NaT,...,2023-02-18,NaT,nan,2023-02-25,NaT,nan,NaN,NaN,NaN,EGV
269,2022-06-28,P21411,NaN,1,"CONAGRA FOODS FAYETTEVILLE, AR",CBC TRANSFER BELT CONVEYOR (ITEM #5),DM,MAR,NaN,NaT,...,2023-02-18,NaT,nan,2023-02-25,NaT,nan,NaN,NaN,NaN,EGV
270,2022-06-28,P21411,NaN,1,"CONAGRA FOODS FAYETTEVILLE, AR",CBC-MD METAL DETECTOR BELT CONVEYOR (ITEM #6),DM,MAR,NaN,NaT,...,2023-02-18,NaT,nan,2023-02-25,NaT,nan,NaN,NaN,NaN,EGV

In [23]:
#Clear Contents in TestTracker1

ws5=wb.sheets['TestTracker1']
ws5.range("A1:CX600").clear_contents()



#Write new data frame to TestTracker1 and make it a table in excel
ws5.range("A1").options(index=False).value = df_final3 #took out for test
#ws5.range("A1").options(index=False).value = df_finaltest #test did not work just fills first lines, does not match to project number or link

#name range for table and get range
tbl_range = ws5.range("A1").expand()

#Create table in excel

# Select your custom range and style the table
tbl = ws5.tables.add(ws5.range(tbl_range), table_style_name='TableStyleMedium6') 



#Autofit Column width for TestTracker1 Worksheet

with xw.App(visible=False) as app:
    wb = xw.Book(path)

    for ws in wb.sheets:
        ws.autofit(axis="columns")


wb.save(path)

In [24]:
#All worked up to this point.  add columns for tracking with formulas.  The create pivot table.  Then done.